---
- name: Load OS specific variables 
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install Zabbix GPG key
  apt_key: url='http://repo.zabbix.com/zabbix-official-repo.key' state=present

- include: Debian.yml
  when: ansible_distribution == 'Debian'

- name: Install zabbix-agent package
  apt: name=zabbix-agent update_cache=yes state=present

- name: Setup zabbix-agentd configuration file
  template: >
    src=zabbix_agentd.conf.j2
    dest=/etc/zabbix/zabbix_agentd.conf
    owner=root
    group=root
    mode=0644
  notify: restart zabbix agent daemon

- name: Setup zabbix-agentd service
  service: name=zabbix-agent state=started enabled=yes